### ISSUE TITLE
ModuleNotFoundError: No module named 'censys.ipv4'

### ISSUE THREAD

**Issue by abidine0** [M0tHs3C/Argo#11]
Python version:

Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

******************************************************************************************************

C:\Users\HP\Desktop\Argo-master>python argo.py
Traceback (most recent call last):
  File "argo.py", line 2, in <module>
    from lib.censysSearch import *
  File "C:\Users\HP\Desktop\Argo-master\lib\censysSearch.py", line 2, in <module>
    import censys.ipv4
ModuleNotFoundError: No module named 'censys.ipv4'

**Comment by abidine0** [comment]
edit; same for py 3.7
