### ISSUE TITLE
No module named 'censys'

### ISSUE THREAD

**Issue by Dliv3q** [M0tHs3C/Argo#18]
Traceback (most recent call last):
  File "C:\Users\izzme\Argo-master\argo.py", line 2, in <module>
    from lib.censysSearch import *
  File "C:\Users\izzme\Argo-master\lib\censysSearch.py", line 2, in <module>
    from censys.search import SearchClient
ModuleNotFoundError: No module named 'censys'
PS C:\Users\izzme\Argo-master>

**Comment by Dliv3q** [comment]
ive "pip install censys" and it still gives me the same error

**Comment by Dliv3q** [comment]
I get Requirement already satisfied: censys in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (2.1.4)
Requirement already satisfied: requests>=2.26.0 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from censys) (2.27.1)
Requirement already satisfied: rich>=10.16.2 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from censys) (12.4.1)
Requirement already satisfied: backoff<3.0.0,>=2.0.1 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from censys) (2.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26.0->censys) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26.0->censys) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26.0->censys) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26.0->censys) (2.0.12)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from rich>=10.16.2->censys) (2.12.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\izzme\appdata\local\programs\python\python310\lib\site-packages (from rich>=10.16.2->censys) (0.9.1)

After pip install censys, and I still get ModuleNotFoundError: No module named 'censys'
