### ISSUE TITLE
I tried to gather hosts from censys and this happened

### ISSUE THREAD

**Issue by dotada** [M0tHs3C/Argo#7]
Traceback (most recent call last):
  File "/home/kali/hikka/Argo/argo.py", line 47, in <module>
    argo.main()
  File "/home/kali/hikka/Argo/argo.py", line 37, in main
    selection(self, int(selectionInput))
  File "/home/kali/hikka/Argo/argo.py", line 15, in selection
    censysSearch.censysGath(self)
  File "/home/kali/hikka/Argo/lib/censysSearch.py", line 20, in censysGath
    secret = censys_list[1]
IndexError: list index out of range

**Comment by M0tHs3C** [comment]
did you save the API keys?

**Comment by dotada** [comment]
> did you save the API keys?

yep

**Comment by M0tHs3C** [comment]
did you save two api keys from censys?
one in top of each other?
