### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by gruz3k** [M0tHs3C/Argo#8]
When selecting Hikvision tester it shows:

Traceback (most recent call last):
  File "/home/kali/Argo/argo.py", line 47, in <module>
    argo.main()
  File "/home/kali/Argo/argo.py", line 37, in main
    selection(self, int(selectionInput))
  File "/home/kali/Argo/argo.py", line 19, in selection
    testerMenu.testerMenu(self)
  File "/home/kali/Argo/modules/testerMenu.py", line 17, in testerMenu
    hikTester.hikTester(self)
  File "/home/kali/Argo/modules/hikvisionTester.py", line 12, in hikTester
    address = host.Host.addressRegex(res)
  File "/home/kali/Argo/host/host.py", line 12, in addressRegex
    ip = match1.group()
AttributeError: 'NoneType' object has no attribute 'group'

Not working on both windows and linux. The V1 version worked perfectly even on raspberrypi.
Sorry if the issue is due to my error :))

**Comment by M0tHs3C** [comment]
didi you test if the host are really up?
as i wrote in the "usage" section?

**Comment by Motoruffka** [comment]
I did test it. I rolled back to V1 and everything is working

**Comment by M0tHs3C** [comment]
v1?
btw u can check really quick the hosts files, if they are empty obviously the code aint gonna work
do you have some host in your files?

**Comment by Motoruffka** [comment]
both hosts.txt and up_hosts.txt are filled with ip's

**Comment by Motoruffka** [comment]
sorry my bad, for V1 I mean the repo from Aug 31, 2020.

**Comment by Motoruffka** [comment]
on Feb 3, 2021 there is Argo v2.0 as the name for one of the commits so I guess V1 is the version that works

**Comment by M0tHs3C** [comment]
can you share the ips file?

**Comment by Motoruffka** [comment]
hosts.txt:
[https://0bin.net/paste/7JY8KjBH#vp26RB-RoZqu+IG8o81bLWw6xtyIxOhspMYOeKBLKNZ](url)

up_hosts.txt
[https://0bin.net/paste/z9u+XRPd#Tt4qYGngnVhMfBqkk44TGuQFlegPoPl3d-uPOJLGJNX](url)

the vuln_hosts.txt file is empty

**Comment by M0tHs3C** [comment]
u can delete this message if u want too

**Comment by M0tHs3C** [comment]
btw i just copied your list and launched a scan and its working fine for me atm

**Comment by Motoruffka** [comment]
For now I can use the older version so that's fine for me
If you ever need help testing new versions of this tool, I will be happy to help :D

**Comment by M0tHs3C** [comment]
be sure to use the latest version, i do periodically fix of bugs
